# Site settings
title: Rogelio Cortes
email: rogelio@rogeliocortes.com
url: https://rogeliocortes.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Full Stack Web Developer - Software Engineer - User Experience Designer"
meta_author: Cortes Rogelio

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2986cc #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Cortes Digital Solutions
  location: Location
  social: Connect with me
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cozmocodes
  - title: instagram
    url: http://instagram.com/rogeliocortes__
  - title: github
    url: http://github.com/rogelio-cortes
  - title: linkedin
    url: http://linkedin.com/in/rogelio-cortes

# Postal address (add as many lines as necessary)
address:
  - line: 750 S Halsted St.
  - line: Chicago, IL 60607

# Credits content
credits: "Written and Developed by Rogelio Cortes. Forked from jeromelachaud's freelancer-theme."

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
